#
# Digital Voice Modem - DFSI Software Configuration
#
# @package DVM / DFSI Software
#

# Flag indicating whether the host will run as a background or foreground task.
daemon: false

#
# Network Configuration
#
network:
    # Textual Name (Change. 9 characters max )
    identity: MYCALL-01
    # Network Peer ID (Change. Numeric only)
    peerId: 123456
    # Hostname/IP address of FNE master to connect to (same for all).
    address: xxx.xxx.xxx.xxx
    # Port number to connect to (same for all).
    port: 62031
    # FNE access password (same for all).
    password: PASSWORD
    # Additional debug logging
    debug: false
    # Encrypted endpoint networking
    encrypted: false
    # Pre-shared key for encrypted networking (AES-256 32-byte hex keystring)
    presharedKey: "000102030405060708090A0B0C0D0E0F000102030405060708090A0B0C0D0E0F"

#
# DFSI Configuration
#
dfsi:
    # Mode
    #   1 - UDP DFSI to DVM FNE (TODO: Implement this)
    #   2 - Serial DFSI to DVM FNE (Using DVM-V24 adapter board)
    #   3 - Serial DFSI to UDP DFSI (TODO: Implement this)
    mode: 2

    # Flag enabling "the" Manufacturer standard of RTP.
    theManufacturer: true

    # P25 buffer size in bytes (don't change this unless you have a good reason to)
    # Default of 3060 is 10 full LDU1/2s worth of data
    p25BufferSize: 3060

    udp:
        # Time in seconds between heartbets to DFSI peers.
        heartbeat: 5
        # Flag disabling control connection establishment.
        noConnectionEstablishment: false
        # Local DFSI RTP Port number.
        localRtpPort: 27500
        # Remote RFSS DFSI Hostname/IP address of FNE master to connect to.
        remoteDfsiAddress: 127.0.0.1
        # Remote DFSI Control Port number to connect to.
        remoteControlPort: 27000
        # Remote DFSI RTP Port number to connect to.
        remoteRtpPort: 27500

    serial:
        # Modem port type.
        portType: "uart" # Valid values are "null", and "uart"
        # Serial configuration for serial DFSI
        port: "/dev/ttyACM0"
        #
        baudrate: 115200
        # RT/RT flag enabled (0x02) or disabled (0x04)
        #rtrt: false
        rtrt: true
        # Use the DIU source flag (0x00) instead of the quantar source flag (0x02)
        diu: false
        # Jitter buffer length in ms
        jitter: 200
        # Debug logging
        debug: false
        # Trace logging (prints lots of data)
        trace: false

    # Timer which will reset local/remote call flags if frames aren't received longer than this time in ms
    callTimeout: 200

#
# Logging Configuration
#   Logging Levels:
#     1 - Debug
#     2 - Message
#     3 - Informational
#     4 - Warning
#     5 - Error
#     6 - Fatal
#
log:
    # Console display logging level (used when in foreground).
    displayLevel: 1
    # File logging level.
    fileLevel: 5
    # Flag indicating file logs should be sent to syslog instead of a file.
    useSyslog: false
    # Full path for the directory to store the log files.
    filePath: /opt/dvm/log
    # Full path for the directory to store the activity log files.
    activityFilePath: /opt/dvm/log
    # Log filename prefix.
    fileRoot: dvmdfsi
